FROM python:3.9-slim

RUN pip install mlflow

ENV PYSPARK_PIN_THREAD=false

RUN mkdir -p /mlflow

EXPOSE 5000

CMD ["mlflow", "server", "--backend-store-uri", "/mlflow", "--default-artifact-root", "/mlflow", "--host", "0.0.0.0"]
